apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: reader-role
  namespace: default
subjects:
- kind: User
  name: devnet
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: reader-role
  apiGroup: rbac.authorization.k8s.io
